/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ciclistas;
import modelo.Pedal;

/**
 *
 * @author jonas
 */
public class GuiListPedais extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiListPedais
     */
    public GuiListPedais() {
        initComponents();
        
        setTitle("Lista dos Pedalantes Cadastrados");
        showListFull();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEditar = new javax.swing.JPanel();
        jTextValor = new javax.swing.JTextField();
        jTextContaDestino = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jLabelContaDestino = new javax.swing.JLabel();
        jLabelContaOrigem = new javax.swing.JLabel();
        jTextContaOrigem = new javax.swing.JTextField();
        jButtonPagar = new javax.swing.JButton();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTextPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonTransferir = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);

        jPanelEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transferência", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTextValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextValor.setEnabled(false);

        jTextContaDestino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextContaDestino.setEnabled(false);

        jLabelValor.setText("Valor");

        jLabelContaDestino.setText("Conta Destino");

        jLabelContaOrigem.setText("Origem");

        jTextContaOrigem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextContaOrigem.setEnabled(false);

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextValor)
                    .addComponent(jTextContaDestino)
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContaDestino)
                            .addComponent(jLabelValor)
                            .addComponent(jLabelContaOrigem))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jTextContaOrigem))
                .addContainerGap())
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelContaOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonPagar.setText("Pagar");
        jButtonPagar.setEnabled(false);
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Número da Conta", "Saldo em Carteira", "Assinatura"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jTextPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisaActionPerformed(evt);
            }
        });

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonTransferir.setText("Trasferir");
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Atualizar tabela");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Valores Padrão");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTransferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonTransferir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefresh)
                    .addComponent(jToggleButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPagar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
       limparTabela();
       showListFull();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        pesquisar();
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jTextPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisaActionPerformed
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_jTextPesquisaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        inicializarLista();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        prepareTranferencia(true);
    }//GEN-LAST:event_jButtonTransferirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        // TODO add your handling code here:
        transferir();
    }//GEN-LAST:event_jButtonPagarActionPerformed
    
    Ciclistas ciclista = new Ciclistas();
    protected ArrayList<Pedal> varLista = ciclista.listarPedais();
    String numContaOrigem = "";
    
    
    DefaultTableModel dtm = new DefaultTableModel(
              new Object[][]{},
              new Object[]{"Nome","Número da Conta", "Saldo em Carteira", "Assinatura"});

    
    
    private DefaultTableModel preencherTabela(ArrayList<Pedal> lista){
        
        for(int i = 0; i < lista.size(); i++ ){
            
            dtm.addRow(new String []{
                
                String.valueOf(lista.get(i).getNome()),
                String.valueOf(lista.get(i).getNumeroConta()),
                String.valueOf(lista.get(i).getSaldo()),
                String.valueOf(lista.get(i).GetAssinatura())
            });
        }
        return dtm;
    }
    
    private void showListFull(){
        jTable.setModel(preencherTabela(varLista));
    }
    
    private void limparTabela(){
        dtm.setNumRows(0);
    }
    
    private boolean pesquisar(){
        
        String pesquisa = jTextPesquisa.getText();
        limparTabela();
        
        if(pesquisa.equals("")){
            showListFull();
            return false;
        }
        
        jTable.setModel(preencherTabela(ciclista.procurar(pesquisa)));
        
        return true;
    }
    
    private boolean excluir(){
        int row = jTable.getSelectedRow();
        
        if(row < 0){
            JOptionPane.showMessageDialog(null,
                    "Selecione algum item da tabela.",
                    "Linha inválida",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        
        if(ciclista.remover(jTable.getValueAt(row, 1).toString())){
            JOptionPane.showMessageDialog(null,
                    "Pedal excluido com Sucesso.",
                    "Excluido",
                    JOptionPane.PLAIN_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(null,
                    "Pedal não pode ser excluido.",
                    "Algo errado ocorreu...",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        limparTabela();
        showListFull();
        return true;
    }
    
    private void inicializarLista(){
        Pedal padrao = new Pedal();
        Pedal padrao2 = new Pedal();
        Pedal padrao3 = new Pedal();
        Pedal padrao4 = new Pedal();
        Pedal padrao5 = new Pedal();
        
        padrao.setNome("teste1");
        padrao.setNumeroConta("111");
        padrao.creditar(11.10);
        ciclista.inserir(padrao);
        padrao2.setNome("teste2");
        padrao2.setNumeroConta("222");
        padrao2.creditar(22.20);
        ciclista.inserir(padrao2);
        padrao3.setNome("teste3");
        padrao3.setNumeroConta("333");
        padrao3.creditar(33.30);
        ciclista.inserir(padrao3);
        padrao4.setNome("teste4");
        padrao4.setNumeroConta("444");
        padrao4.creditar(44.40);
        ciclista.inserir(padrao4);
        padrao5.setNome("teste5");
        padrao5.setNumeroConta("555");
        padrao5.creditar(555.50);
        padrao5.setIsPremium(true);
        ciclista.inserir(padrao5);
        
        varLista = ciclista.listarPedais();
        
        showListFull();
    }
    
    private boolean prepareTranferencia(boolean isTranferir){
        
        if(isTranferir){

            int row = jTable.getSelectedRow();

            if(row < 0){

                JOptionPane.showMessageDialog(null,
                        "Selecione algum item da tabela.",
                        "Linha inválida",
                        JOptionPane.PLAIN_MESSAGE);
                return false;
            }

            jTextValor.setEnabled(true);
            jTextContaDestino.setEnabled(true);
            jButtonPagar.setEnabled(true);

            jTextPesquisa.setEnabled(false);
            jButtonTransferir.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonPesquisa.setEnabled(false);
            jTable.setEnabled(false);
            jButtonRefresh.setEnabled(false);

            numContaOrigem = jTable.getValueAt(row, 1).toString();

            jTextContaOrigem.setText(numContaOrigem + " - " + 
                    jTable.getValueAt(row, 0).toString());

            jTextValor.setText(jTable.getValueAt(row, 2).toString());


            return true;
        }else{
            jTextValor.setEnabled(false);
            jTextContaDestino.setEnabled(false);
            jButtonPagar.setEnabled(false);

            jTextPesquisa.setEnabled(true);
            jButtonTransferir.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonPesquisa.setEnabled(true);
            jTable.setEnabled(true);
            jButtonRefresh.setEnabled(true);

            jTextContaOrigem.setText("");
            jTextContaDestino.setText("");
            jTextValor.setText("");
            
            
            return true;
        }
        
    }
    
    private boolean transferir(){
        double valor = 0;
        String numContaDestino = jTextContaDestino.getText();
        String msg = "";
        String title = "Ocorreu um erro ao Tranferir";
        
        if(numContaDestino.isEmpty()){
            JOptionPane.showMessageDialog(null,
                    "Insira o número da conta de Destino.",
                    "Campo Obrigatório",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        
        if(!jTextValor.getText().isEmpty()){
            valor = Double.parseDouble(jTextValor.getText().replace(",", "."));
        }
        
        msg = ciclista.transferir(numContaOrigem, valor, numContaDestino);
        
        
        if(msg.equals("")){
            msg = "Tranferência realizada com sucesso!";
            title = "Transeferido";
            limparTabela();
            showListFull();
            prepareTranferencia(false);
        }
        
        JOptionPane.showMessageDialog(null,
                    msg,
                    title,
                    JOptionPane.PLAIN_MESSAGE);
        
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabelContaDestino;
    private javax.swing.JLabel jLabelContaOrigem;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextContaDestino;
    private javax.swing.JTextField jTextContaOrigem;
    private javax.swing.JTextField jTextPesquisa;
    private javax.swing.JTextField jTextValor;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
