/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.Ciclistas;

/**
 *
 * @author jonas
 */
public class GuiPaginaPedal extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiPaginaPedal
     */
    public GuiPaginaPedal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPedalar = new javax.swing.JPanel();
        jLabelNumeroConta = new javax.swing.JLabel();
        jTextNumeroConta = new javax.swing.JTextField();
        jLabelInfoNome = new javax.swing.JLabel();
        jLabelKilometros = new javax.swing.JLabel();
        jTextKilometros = new javax.swing.JTextField();
        jButtonPedalar = new javax.swing.JButton();
        jPanelTransferir = new javax.swing.JPanel();
        jLabelContaDestino = new javax.swing.JLabel();
        jTextContaDestino = new javax.swing.JTextField();
        jLabelInfoSaldo = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        jButtonTransferir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Portal do Pedal");

        jPanelPedalar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedalar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabelNumeroConta.setText("Número da Conta");

        jTextNumeroConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNumeroContaKeyReleased(evt);
            }
        });

        jLabelInfoNome.setForeground(new java.awt.Color(134, 134, 134));
        jLabelInfoNome.setText("Informe o número da conta");

        jLabelKilometros.setText("Quantidade de Kms");

        jTextKilometros.setEnabled(false);
        jTextKilometros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKilometrosActionPerformed(evt);
            }
        });

        jButtonPedalar.setText("Pedalar");
        jButtonPedalar.setEnabled(false);
        jButtonPedalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedalarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedalarLayout = new javax.swing.GroupLayout(jPanelPedalar);
        jPanelPedalar.setLayout(jPanelPedalarLayout);
        jPanelPedalarLayout.setHorizontalGroup(
            jPanelPedalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedalarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPedalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNumeroConta)
                    .addComponent(jTextKilometros)
                    .addGroup(jPanelPedalarLayout.createSequentialGroup()
                        .addGroup(jPanelPedalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroConta)
                            .addComponent(jLabelKilometros))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonPedalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInfoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPedalarLayout.setVerticalGroup(
            jPanelPedalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedalarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNumeroConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoNome)
                .addGap(18, 18, 18)
                .addComponent(jLabelKilometros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPedalar)
                .addContainerGap())
        );

        jPanelTransferir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transferência", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabelContaDestino.setText("Conta Destino");

        jTextContaDestino.setEnabled(false);

        jLabelInfoSaldo.setForeground(new java.awt.Color(134, 134, 134));
        jLabelInfoSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInfoSaldo.setText("Seu saldo é: 0,00");

        jLabelValor.setText("Valor");

        jTextValor.setEnabled(false);
        jTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorActionPerformed(evt);
            }
        });

        jButtonTransferir.setText("Transferir");
        jButtonTransferir.setEnabled(false);
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransferirLayout = new javax.swing.GroupLayout(jPanelTransferir);
        jPanelTransferir.setLayout(jPanelTransferirLayout);
        jPanelTransferirLayout.setHorizontalGroup(
            jPanelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransferirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfoSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextContaDestino)
                    .addComponent(jButtonTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTransferirLayout.createSequentialGroup()
                        .addComponent(jLabelContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addComponent(jTextValor)
                    .addComponent(jLabelValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTransferirLayout.setVerticalGroup(
            jPanelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransferirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelContaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoSaldo)
                .addGap(18, 18, 18)
                .addComponent(jLabelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButtonTransferir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPedalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanelTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPedalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Ciclistas ciclistas = new Ciclistas();
    
    private void jTextNumeroContaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumeroContaKeyReleased
        getConta();
    }//GEN-LAST:event_jTextNumeroContaKeyReleased

    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        // TODO add your handling code here:
        transferir();
        
    }//GEN-LAST:event_jButtonTransferirActionPerformed

    private void jTextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorActionPerformed
        // TODO add your handling code here:
        transferir();
    }//GEN-LAST:event_jTextValorActionPerformed

    private void jButtonPedalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedalarActionPerformed
        // TODO add your handling code here:
        pedalar();
    }//GEN-LAST:event_jButtonPedalarActionPerformed

    private void jTextKilometrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKilometrosActionPerformed
        // TODO add your handling code here:
        pedalar();
    }//GEN-LAST:event_jTextKilometrosActionPerformed

    
    private void getConta(){
        int posicao = ciclistas.getPosicaoPedalByConta(jTextNumeroConta.getText());
        
        if(posicao >= 0){
            jLabelInfoNome.setText("Olá " + ciclistas.listarPedais().get(posicao).getNome());
            atualizaLabelSaldo(posicao);
            jTextContaDestino.setEnabled(true);
            jTextKilometros.setEnabled(true);
            jTextValor.setEnabled(true);
            jButtonPedalar.setEnabled(true);
            jButtonTransferir.setEnabled(true);
            
        }else{
            setarValoresPadrao();
        }
    }
    
    private boolean pedalar(){
        int posicao = ciclistas.getPosicaoPedalByConta(jTextNumeroConta.getText());
        double custoPedal = 0;
        
        if(!jTextKilometros.getText().isEmpty()){
            custoPedal = Double.parseDouble(jTextKilometros.getText().replace(",", ".")) / 2;
        }
        
        if(custoPedal == 0){
            JOptionPane.showMessageDialog(null,
                    "O Campo Kilometragem não pode ser vazio.",
                    "Kilometragem inválida",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        
        int opcao = JOptionPane.showConfirmDialog(null,
                "O valor para essa distância é " + formatarDouble(custoPedal) + "\nVocê confirma esses valores?", 
                "Confirmar pagamento", 
                JOptionPane.YES_NO_OPTION);
        // sim é == 0
        if(opcao != 0){
            return false;
        }
        
        ciclistas.listarPedais().get(posicao).pedalar(custoPedal,ciclistas.listarPedais().get(posicao).GetIsPremium());
        atualizaLabelSaldo(posicao);
        JOptionPane.showMessageDialog(null,
                    "Tudo certo, pode começar a pedalar, bom passeio!",
                    "Passeio garantido.",
                    JOptionPane.PLAIN_MESSAGE);
        
        
        return true;
    }

    private boolean transferir(){
        double valor = 0;
        String numContaDestino = jTextContaDestino.getText();
        String msg = "";
        String title = "Ocorreu um erro ao Tranferir";
        
        if(numContaDestino.isEmpty()){
            JOptionPane.showMessageDialog(null,
                    "Insira o número da conta de Destino.",
                    "Campo Obrigatório",
                    JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        
        if(!jTextValor.getText().isEmpty()){
            valor = Double.parseDouble(jTextValor.getText().replace(",", "."));
        }
        
        msg = ciclistas.transferir(jTextNumeroConta.getText(), valor, numContaDestino);
        
        
        if(msg.equals("")){
            msg = "Tranferência realizada com sucesso!";
            title = "Transeferido";
            int posicao = ciclistas.getPosicaoPedalByConta(jTextNumeroConta.getText());
            atualizaLabelSaldo(posicao);
        }
        
        JOptionPane.showMessageDialog(null,
                    msg,
                    title,
                    JOptionPane.PLAIN_MESSAGE);
        
        
        return true;
    }
   
     private void setarValoresPadrao(){
        jTextContaDestino.setText("");
        jTextKilometros.setText("");
        jTextValor.setText("");
        jLabelInfoNome.setText("Informe o número da conta");
        jLabelInfoSaldo.setText("Seu saldo é: 0,00");
        
        jTextContaDestino.setEnabled(false);
        jTextKilometros.setEnabled(false);
        jTextValor.setEnabled(false);
        jButtonPedalar.setEnabled(false);
        jButtonTransferir.setEnabled(false);
    }
    
    private String formatarDouble(double valor){
        return String.format("%.2f", valor);
    }
    
    private void atualizaLabelSaldo(int posicao){
        jLabelInfoSaldo.setText("Seu saldo é: " + formatarDouble(ciclistas.listarPedais().get(posicao).getSaldo()) 
                + " limite: " + formatarDouble(ciclistas.listarPedais().get(posicao).getLimite()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPedalar;
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabelContaDestino;
    private javax.swing.JLabel jLabelInfoNome;
    private javax.swing.JLabel jLabelInfoSaldo;
    private javax.swing.JLabel jLabelKilometros;
    private javax.swing.JLabel jLabelNumeroConta;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelPedalar;
    private javax.swing.JPanel jPanelTransferir;
    private javax.swing.JTextField jTextContaDestino;
    private javax.swing.JTextField jTextKilometros;
    private javax.swing.JTextField jTextNumeroConta;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables
}
